name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-build-artifact:
    name: Lint Build and Store Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.1'
      
      - name: Install dependencies
        run: |
          npm install --force

      - name: Run ESLint on code
        run: |
          npx eslint '**/*.js'
      
      - name: Build code
        run: |
          npm run build 

      - name: Zip code build
        run: |
          zip -r code-build.zip .

      - name: Upload Code Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-build
          path: code-build.zip
